-- Add AI generation capabilities to ports system
-- Date: 2026-01-25
-- Purpose: Enable AI-powered port guide generation alongside existing manual upload

-- =====================================================
-- 1. ADD AI GENERATION TRACKING COLUMNS
-- =====================================================

-- Generation tracking
ALTER TABLE ports ADD COLUMN IF NOT EXISTS source_urls JSONB DEFAULT '[]';
COMMENT ON COLUMN ports.source_urls IS 'Array of URLs used for research/generation: [{ url, title, scraped_at }]';

ALTER TABLE ports ADD COLUMN IF NOT EXISTS last_refreshed_at TIMESTAMPTZ;
COMMENT ON COLUMN ports.last_refreshed_at IS 'Timestamp of last AI refresh (null = never refreshed)';

ALTER TABLE ports ADD COLUMN IF NOT EXISTS needs_refresh BOOLEAN DEFAULT false;
COMMENT ON COLUMN ports.needs_refresh IS 'Flag: content is stale and should be refreshed';

ALTER TABLE ports ADD COLUMN IF NOT EXISTS refresh_due_date TIMESTAMPTZ;
COMMENT ON COLUMN ports.refresh_due_date IS 'Date when content should be refreshed (6 months after last_refreshed_at)';

-- =====================================================
-- 2. ADD REVIEW WORKFLOW COLUMNS
-- =====================================================

ALTER TABLE ports ADD COLUMN IF NOT EXISTS reviewed_by UUID;
COMMENT ON COLUMN ports.reviewed_by IS 'User ID who reviewed and approved the guide';

ALTER TABLE ports ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ;
COMMENT ON COLUMN ports.reviewed_at IS 'Timestamp when guide was reviewed and approved';

-- =====================================================
-- 3. ADD GENERATION METADATA
-- =====================================================

ALTER TABLE ports ADD COLUMN IF NOT EXISTS ai_generated BOOLEAN DEFAULT false;
COMMENT ON COLUMN ports.ai_generated IS 'True if guide was generated by AI (vs manual markdown upload)';

ALTER TABLE ports ADD COLUMN IF NOT EXISTS generation_version INTEGER DEFAULT 0;
COMMENT ON COLUMN ports.generation_version IS 'Increments each time AI regenerates content (0 = manual/original)';

-- =====================================================
-- 4. ADD MISSING COLUMNS THAT CODE EXPECTS
-- =====================================================

ALTER TABLE ports ADD COLUMN IF NOT EXISTS show_in_menu BOOLEAN DEFAULT false;
COMMENT ON COLUMN ports.show_in_menu IS 'Show in website navigation menu';

ALTER TABLE ports ADD COLUMN IF NOT EXISTS is_complete BOOLEAN DEFAULT false;
COMMENT ON COLUMN ports.is_complete IS 'Guide is complete and ready for publication';

-- =====================================================
-- 5. CREATE INDEXES FOR PERFORMANCE
-- =====================================================

-- Index for finding stale ports
CREATE INDEX IF NOT EXISTS idx_ports_needs_refresh 
ON ports(needs_refresh) 
WHERE needs_refresh = true;

-- Index for finding ports due for refresh
CREATE INDEX IF NOT EXISTS idx_ports_refresh_due 
ON ports(refresh_due_date) 
WHERE refresh_due_date IS NOT NULL AND status = 'published';

-- Index for AI-generated ports
CREATE INDEX IF NOT EXISTS idx_ports_ai_generated 
ON ports(ai_generated) 
WHERE ai_generated = true;

-- =====================================================
-- 6. CREATE HELPER FUNCTION TO FLAG STALE PORTS
-- =====================================================

CREATE OR REPLACE FUNCTION public.flag_stale_ports()
RETURNS TABLE (
  port_id UUID,
  port_name TEXT,
  last_refreshed TIMESTAMPTZ,
  days_since_refresh INTEGER
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
BEGIN
  -- Flag ports that haven't been refreshed in 6 months
  UPDATE ports
  SET 
    needs_refresh = true,
    refresh_due_date = COALESCE(last_refreshed_at, created_at) + INTERVAL '6 months'
  WHERE 
    status = 'published'
    AND (
      last_refreshed_at IS NULL 
      OR last_refreshed_at < NOW() - INTERVAL '6 months'
    )
    AND needs_refresh = false;
  
  -- Return list of flagged ports
  RETURN QUERY
  SELECT 
    id,
    name,
    COALESCE(last_refreshed_at, created_at) AS last_refreshed,
    EXTRACT(DAY FROM NOW() - COALESCE(last_refreshed_at, created_at))::INTEGER AS days_since_refresh
  FROM ports
  WHERE needs_refresh = true
  ORDER BY last_refreshed_at ASC NULLS FIRST;
END;
$$;

COMMENT ON FUNCTION public.flag_stale_ports IS 'Flags published ports that are 6+ months old and returns list';

-- =====================================================
-- 7. CREATE HELPER FUNCTION TO RECORD AI GENERATION
-- =====================================================

CREATE OR REPLACE FUNCTION public.record_port_generation(
  p_port_id UUID,
  p_source_urls JSONB DEFAULT '[]'
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
BEGIN
  UPDATE ports
  SET 
    ai_generated = true,
    generation_version = generation_version + 1,
    last_refreshed_at = NOW(),
    needs_refresh = false,
    refresh_due_date = NOW() + INTERVAL '6 months',
    source_urls = p_source_urls,
    updated_at = NOW()
  WHERE id = p_port_id;
END;
$$;

COMMENT ON FUNCTION public.record_port_generation IS 'Records AI generation metadata after successful generation';

-- =====================================================
-- 8. GRANT PERMISSIONS
-- =====================================================

-- Functions should be callable by authenticated users (CRM)
GRANT EXECUTE ON FUNCTION public.flag_stale_ports TO authenticated;
GRANT EXECUTE ON FUNCTION public.record_port_generation TO authenticated;

-- Migration complete
